apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-name-dynamic-resource
  description: Resource Dynamic APIs
  tags:
    - dynamic
spec:
  type: openapi
  lifecycle: dynamic
  owner: team-d
  definition:
    $text: https://test-amorphie-resource.burgan.com.tr/swagger/v1/swagger.yaml
